before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends \
      xvfb \
      libwebkitgtk-dev \
      libjpeg-dev \
      libtiff-dev \
      libgtk2.0-dev \
      libsdl1.2-dev \
      libgstreamer-plugins-base0.10-dev \
      freeglut3 \
      freeglut3-dev \
      libnotify-dev

test:2.7:
  image: python:2.7

  script:
    - cat requirements.txt | xargs -n 1 pip install
    - xvfb-run python setup.py test

test:3.6:
  image: python:3.6

  script:
    - cat requirements.txt | xargs -n 1 pip install
    - xvfb-run python setup.py test
