test:2.7:
  image: fsleyes-py27

  script:
    - cat requirements.txt | xargs -n 1 pip install
    - xvfb-run python setup.py test
    - coverage report -m

test:3.6:
  image: fsleyes-py36

  script:
    - cat requirements.txt | xargs -n 1 pip install
    - xvfb-run python setup.py test
    - coverage report -m
